### ISSUE TITLE
Complete Migration from closed beta

### ISSUE THREAD

**Issue by Praesidiarius** [OnePlc/PLC_X_Task#1]
### Feature Request

Rebase Task on the newest opensource skeleton.

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | no

#### Summary
Rebase Task on the newest opensource skeleton.

**Comment by JBinggi** [comment]
Upload file function missing

**Comment by JBinggi** [comment]
Rebase Task completed.
Extended funtionality goes into a submodule
